<?php
    $viewClosed = false;
    if ($_GET["name"] != null) {
        $viewClosed = true;
    }
    //TODO: get batches list
    $batches = array();
?>

<!-- TABLE -->
<table class="grid">
    <tr>
        <th>
            <span>View Closed Batches</span><input type="checkbox" />
            <button id="add-batch" class="btn btn-success">ADD BATCH</button>
        </th>
    </tr>
<?php foreach ($batchesbatch as $batch) { ?>
    <tr class="a-batch-item" data-target="<?= $batch.id ?>">
        <td><?= $batch.name ?></td>
        <td># <?$batch.id ?></td>
        <td>
            <div class="btn-group btn-sm btn-default">
                <button class="btn">view</button>
                <button class="btn">cancel</button>
                <button class="btn">end</button>
                <button class="btn">students</button>
                <button class="btn">email</button>
            </div>
        </td>
    </tr>
<?php } ?>
</table>

<div id="courseDialog" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">New Batch</h4>
            </div>

            <div class="modal-body">
                <h3>NEW BATCH</h3>
            </div>
            
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">CANCEL</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">SUBMIT</button>
            </div>
        </div>
    </div>
</div>