<?php
    $viewClosed = false;
    if ($_GET["closed"] != null) {
        $viewClosed = true;
    }
    //TODO: get data
    $batches = array();
    $courses = array();
    $times = array();
?>

<!-- TABLE -->
<table class="grid">
    <tr>
        <th colspan="3">
            <span>View Closed Batches</span><input type="checkbox" />
            <button id="add-batch" class="btn btn-success" data-target="#batchDialog" data-toggle="modal">ADD BATCH</button>
        </th>
    </tr>
<?php foreach ($batches as $batch) { ?>
    <tr class="a-batch-item" data-target="<?= $batch.id ?>">
        <td><?= $batch.name ?></td>
        <td># <?$batch.id ?></td>
        <td>
            <div class="btn-group btn-sm btn-default">
                <button class="btn">view</button>
                <button class="btn">cancel</button>
                <button class="btn">end</button>
                <button class="btn">students</button>
                <button class="btn">email</button>
            </div>
        </td>
    </tr>
<?php } ?>
</table>

<div id="batchDialog" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">New Batch</h4>
            </div>

            <div class="modal-body">
                <div class="form-group">
                    <label for="course-id">Course:</label>
                    <select class="form-control" id="course-id">
<?php foreach ($courses as $course) { ?>
                        <option value="<?=$course.id ?>"><?=$course.name ?></option>
<?php } ?>
                    </select>
                </div>
                <div class="form-group">
                    <label for="timeslot">Time:</label>
                    <select class="form-control" id="timeslot">
<?php foreach ($times as $time) { ?>
                        <option value="<?=$time.id?>"><?=$time.text?></option>
<?php } ?>
                    </select>
                </div>
            </div>
            
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">CANCEL</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">SUBMIT</button>
            </div>
        </div>
    </div>
</div>