<?php
    //TODO: get data
    $courses = array();
    $teachers = array();
?>

<!-- TABLE -->
<table class="grid">
    <tr>
        <th>
            <button id="add-course" class="btn btn-success" data-target="#courseDialog" data-toggle="modal">ADD COURSE</button>
        </th>
    </tr>
<?php foreach ($courses as $course) { ?>
    <tr class="a-course-item" data-target="<?= $course.id ?>">
        <td><?= $course.name ?></td>
    </tr>
<?php } ?>
</table>

<div id="courseDialog" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">New Course</h4>
            </div>

            <div class="modal-body">
                <div class="form-group">
                    <label for="course-name">Name:</label>
                    <input type="text" class="form-control" id="course-name" name="course-name">
                </div>
                <div class="form-group">
                    <label for="course-seats">Default Max Seats:</label>
                    <input type="text" class="form-control" id="course-seats" name="course-seats">
                </div>
                <div class="form-group">
                    <label for="course-teach">Teacher:</label>
                    <input type="text" class="form-control" id="course-teach" name="course-teach">
                </div>
            </div>
            
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">CANCEL</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">SUBMIT</button>
            </div>
        </div>
    </div>
</div>